### ISSUE TITLE
What is discovery filed

### ISSUE THREAD

**Issue by floriancastelain** [ncarlier/node-red-contrib-openid#4]
What is the discovery field? Trying with google, I passed https://accounts.google.com/o/oauth2/v2/auth but got a `Bad discovery URL` response.

Some information about that would be appreciated, thanks. # #

**Comment by floriancastelain** [comment]
https://accounts.google.com/.well-known/openid-configuration

**Comment by ncarlier** [comment]
You right. I will add some information. BTW, here other discovery urls : https://github.com/ncarlier/node-red-contrib-auth-oidc/blob/master/README.md#usage
