### ISSUE TITLE
Allow customization of scopes

### ISSUE THREAD

**Issue by ahofman** [ncarlier/node-red-contrib-openid#6]
Currently it looks like the node will always hit the OIDC authorization endpoint with the following hard-coded scopes: `openid email offline_access`. 

I'd like to be able to specify custom scopes in this list, as required by the API I'm accessing. 

Do you accept PRs here?

**Comment by ncarlier** [comment]
It is very welcome :)

**Comment by ncarlier** [comment]
Thanks for your work!
